# OpenManus Java Configuration
openmanus:
  app:
    name: "OpenManus"
    version: "1.0.0"
    workspace-root: "./workspace"
    log-level: "INFO"

  llm:
    default-llm:
      model: "qwen-max"
      base-url: "https://dashscope.aliyuncs.com/compatible-mode/v1/"
      api-type: "openai"
      temperature: 0.7
      max-tokens: 8192
      timeout: 120
      # DashScope API key
      api-key: "sk-9ced5f4658584abe9b786a0876e850c4"

  sandbox:
    type: "docker"
    use-sandbox: false
    image: "python:3.11-slim"
    work-dir: "/workspace"
    memory-limit: "512m"
    cpu-limit: 1.0
    timeout: 120
    network-enabled: true

  browser:
    type: "chrome"
    headless: true
    timeout: 30
    user-agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"

  proxy:
    enabled: false
    http-proxy: ""
    https-proxy: ""

  search:
    engine: "google"
    api-key: ""
    max-results: 10

  # MCP configuration has been removed, now using langchain4j-mcp's DefaultMcpClient directly
  # If you need to use MCP tools, please create DefaultMcpClient in your business code

  runflow:
    enabled: false
    max-steps: 20
    timeout: 300

# Spring Boot Configuration
server:
  port: 8089
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: openmanus-java-web
  
  # Web-related configuration
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0 # Don't cache static resources in development environment

  # JSON configuration
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "Asia/Shanghai"
    default-property-inclusion: NON_NULL
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    property-naming-strategy: SNAKE_CASE
    mapper:
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true

  # WebSocket configuration
  websocket:
    servlet:
      allowed-origins: "*"

# Monitoring configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always

# OpenAPI/Swagger configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

logging:
  level:
    com.openmanus.java: INFO
    root: INFO
    org.springframework.web: DEBUG
