package com.openmanus.java.flow;

import com.openmanus.java.agent.BaseAgent;
import org.bsc.langgraph4j.state.AgentState;
import org.bsc.langgraph4j.state.Channel;
import org.bsc.langgraph4j.state.Channels;
import org.bsc.langgraph4j.state.Reducer;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Represents the state that is passed between nodes in the PlanningFlow graph.
 */
public class PlanningFlowState extends AgentState {

    public PlanningFlowState(Map<String, Object> initData) {
        super(initData);
    }

    public PlanningFlowState() {
        super(Map.of());
    }

    // Schema definition for LangGraph4j
    public static final Map<String, Channel<?>> SCHEMA = Map.of(
            "plan", Channels.base(() -> null),
            "currentUserRequest", Channels.base(() -> null),
            "agents", Channels.base(() -> new HashMap<>()),
            "currentStepIndex", Channels.base(() -> 0),
            "executionHistory", Channels.appender(ArrayList::new));

    // The plan generated by the planner agent
    private Plan plan;

    // The initial user request
    private String currentUserRequest;

    // A map of available agents, keyed by their names
    private Map<String, BaseAgent> agents;

    // The index of the current step in the plan
    private int currentStepIndex = 0;

    // A history of execution results
    private List<String> executionHistory;

    // Getters and setters
    public Plan getPlan() { return plan; }
    public void setPlan(Plan plan) { this.plan = plan; }
    
    public String getCurrentUserRequest() { return currentUserRequest; }
    public void setCurrentUserRequest(String currentUserRequest) { this.currentUserRequest = currentUserRequest; }
    
    public Map<String, BaseAgent> getAgents() { return agents; }
    public void setAgents(Map<String, BaseAgent> agents) { this.agents = agents; }
    
    public int getCurrentStepIndex() { return currentStepIndex; }
    public void setCurrentStepIndex(int currentStepIndex) { this.currentStepIndex = currentStepIndex; }
    
    public List<String> getExecutionHistory() { return executionHistory; }
    public void setExecutionHistory(List<String> executionHistory) { this.executionHistory = executionHistory; }

    // A simple plan class
    public static class Plan {
        private List<Step> steps;
        
        public Plan() {}
        public Plan(List<Step> steps) { this.steps = steps; }
        
        public List<Step> getSteps() { return steps; }
        public void setSteps(List<Step> steps) { this.steps = steps; }
    }

    // A single step in the plan
    public static class Step {
        private String agentName;
        private String task;
        
        public Step() {}
        public Step(String agentName, String task) {
            this.agentName = agentName;
            this.task = task;
        }
        
        public String getAgentName() { return agentName; }
        public void setAgentName(String agentName) { this.agentName = agentName; }
        
        public String getTask() { return task; }
        public void setTask(String task) { this.task = task; }
    }
}
