name: Feature Request
description: 建议一个新功能或改进
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间建议新功能！我们重视您的反馈。

  - type: input
    id: contact
    attributes:
      label: 联系方式
      description: 如果我们需要跟进，如何联系您？
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: problem
    attributes:
      label: 问题描述
      description: 您遇到了什么问题？这个功能将如何解决它？
      placeholder: 我在使用OpenManus时遇到了...的问题
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 建议的解决方案
      description: 您希望看到什么功能或改进？
      placeholder: 我希望OpenManus能够...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 您是否考虑过其他解决方案？
      placeholder: 我也考虑过...
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: 功能类别
      description: 这个功能属于哪个类别？
      options:
        - AI代理功能
        - 工具扩展
        - 用户界面
        - 性能优化
        - 安全性
        - 文档
        - 其他 (请在下方说明)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 优先级
      description: 您认为这个功能的优先级如何？
      options:
        - 低 (Nice to have)
        - 中 (Would be helpful)
        - 高 (Important for my workflow)
        - 紧急 (Blocking my work)
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: 使用场景
      description: 描述一下您将如何使用这个功能
      placeholder: |
        作为一个[用户类型]，我想要[功能]，这样我就可以[目标]。
        
        具体的使用步骤：
        1. 我会...
        2. 然后...
        3. 最后...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 其他上下文
      description: 添加任何其他上下文、截图或示例
    validations:
      required: false

  - type: checkboxes
    id: implementation
    attributes:
      label: 实现意愿
      description: 您是否愿意帮助实现这个功能？
      options:
        - label: 我愿意提交Pull Request来实现这个功能
        - label: 我可以帮助测试这个功能
        - label: 我可以帮助完善功能设计
        - label: 我可以提供更多的使用场景和反馈

  - type: checkboxes
    id: terms
    attributes:
      label: 检查清单
      description: 在提交之前，请确认以下事项
      options:
        - label: 我已经搜索了现有的Issues，确认这不是重复的功能请求
          required: true
        - label: 我已经阅读了CONTRIBUTING.md
          required: true
        - label: 这个功能符合项目的目标和范围
          required: true 